branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libxml2

before_script:
  - chmod +x ./_build.sh
      
script:
  - ./_build
  - git config --global user.email "stephane.trainel@gmail.com"
  - git config --global user.name "Stéphane Trainel"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - rm -fr ./output/*
  - cp -r ./Supports_formations/m1_socle/_book ./output/
  - mv ./output/_book ./output/m1
  - cp -r ./Supports_formations/m1_socle/_bookdown_files ./output/m1/
  - cp -r ./Supports_formations/m2_preparation_donnees/_book ./output/
  - mv ./output/_book ./output/m2
  - cp -r ./Supports_formations/m2_preparation_donnees/_bookdown_files ./output/m2/
  - cp -r ./assets ./semantic index.html ./output/
  - cd output
  - git add --all -f ./*
  - git commit --allow-empty -m"Update site"
  - git push origin gh-pages
 