branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes

script:
  - git config --global user.email "stephane.trainel@gmail.com"
  - git config --global user.name "Stéphane Trainel"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - cp ./Supports_formations/m1_socle/*.Rmd ./output
  - cp ./Supports_formations/m1_socle/*.bib ./output
  - cp -r ./Supports_formations/m1_socle/images ./output/
  - cd output
  - Rscript -e "rmarkdown::render('index.Rmd')"
  - Rscript -e "rmarkdown::render('01-intro.Rmd')"
  - Rscript -e "rmarkdown::render('02-interface.Rmd')"
  - Rscript -e "rmarkdown::render('03-import.Rmd')"
  - Rscript -e "rmarkdown::render('03b-get_started.Rmd')"
  - Rscript -e "rmarkdown::render('04-manip.Rmd')"
  - Rscript -e "rmarkdown::render('05-stats.Rmd')"
  - Rscript -e "rmarkdown::render('06-graph.Rmd')"
  - Rscript -e "rmarkdown::render('07-export.Rmd')"
  - Rscript -e "rmarkdown::render('08-rbase.Rmd')"
  - git add --all -f ./*
  - git commit --allow-empty -m"Update site"
  - git push origin gh-pages
 