branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

script:
  - git config --global user.email "stephane.trainel@gmail.com"
  - git config --global user.name "Stéphane Trainel"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - cd ./Supports_formations/m1_socle/
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - cd ../..
  - rm -fr ./output/*
  - mkdir ./output/m1
  - cp -r ./Supports_formations/m1_socle/_book ./output/m1/
  - cp -r ./Supports_formations/m1_socle/_bookdown_files ./output/m1/
  - git add --all -f ./*
  - git commit --allow-empty -m"Update site"
  - git push origin gh-pages
 