branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

script:
  - git config --global user.email "stephane.trainel@gmail.com"
  - git config --global user.name "Stéphane Trainel"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - cp ./Supports_formations/m1_socle/*.Rmd ./output
  - cp ./Supports_formations/m1_socle/*.bib ./output
  - cp -r ./Supports_formations/m1_socle/images ./output/
  - cp -r ./Supports_formations/m1_socle/data ./output/
  - cd output
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - git mv _book m1
  - git add --all -f ./*
  - git commit --allow-empty -m"Update site"
  - git push origin gh-pages
 