branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libxml2
      - cargo

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
      
script:
  - ./_build.sh
  - ./_deploy.sh
