branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

script:
  - git config --global user.email "stephane.trainel@gmail.com"
  - git config --global user.name "Stéphane Trainel"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - git rm -fr .
  - cp ./Supports_formations/m1_socle/*.Rmd ./output
  - cp ./Supports_formations/m1_socle/*.bib ./output
  - cp -r ./Supports_formations/m1_socle/images ./output/
  - cp -r ./Supports_formations/m1_socle/data ./output/
  - cd output
  - Rscript -e "rmarkdown::render('index.Rmd')"
  - Rscript -e "rmarkdown::render('01-introduction.Rmd')"
  - Rscript -e "rmarkdown::render('02-generalite.Rmd')"
  - Rscript -e "rmarkdown::render('03-interface.Rmd')"
  - Rscript -e "rmarkdown::render('04-premier_jeu_donnees.Rmd')"
  - Rscript -e "rmarkdown::render('05-get_started.Rmd')"
  - Rscript -e "rmarkdown::render('06-manip.Rmd')"
  - Rscript -e "rmarkdown::render('07-stats.Rmd')"
  - Rscript -e "rmarkdown::render('08-graph.Rmd')"
  - Rscript -e "rmarkdown::render('09-export.Rmd')"
  - Rscript -e "rmarkdown::render('10-rbase.Rmd')"
  - git add --all -f ./*
  - git commit --allow-empty -m"Update site"
  - git push origin gh-pages
 